Samuel_Yazie_SQL_Lab2/Models/ErrorViewModel.cs
namespace Samuel_Yazie_SQL_Lab2.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Samuel_Yazie_SQL_Lab2/Controllers/EventsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using IPBLL;
using IPENTITES;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace Samuel_Yazie_SQL_Lab2.Controllers
{
    public class EventsController : Controller
    {
        // GET: /<controller>/
        public IActionResult Index()
        {
            EventsService es = new EventsService();
            var events = es.GetEvents();
            return View(events);
        }

        public IActionResult CreateEventsView()
        {
            return View();
        }

        [HttpPost]
        public IActionResult CreateEventsView(Events events)
        {
            EventsService es = new EventsService();
            if (es.AddEventsService(events))
            {
                ViewBag.Message = "Event added successfully";
            }
            return View();
        }

        /// <summary>
        /// EditEventView is responsible for fetching the event with the given eventId and displaying it in the view
        /// </summary>
        /// <param name="eventId"></param>
        /// <returns></returns>
        public IActionResult EditEventsView(int eventId)
        {
            EventsService eventService = new EventsService();
            // Fetch all the events and find the event with the given eventId
            var @event = eventService.GetEvents().Find(e => e.EventId == eventId);

            return View(@event);
        }

        /// <summary>
        /// EditEventView is responsible for updating the event with the given eventId and displaying it in the view
        /// and pass that to the service and repository to update the event
        /// </summary>
        /// <param name="event"></param>
        /// <returns></returns>
        [HttpPost]
        public IActionResult EditEventsView(Events @event)
        {
            EventsService eventService = new EventsService();
            if (eventService.UpdateEventsService(@event))
            {
                ViewBag.Message = "Event updated successfully";
            }
            return View();
        }

        public IActionResult DeleteEvent(int eventId)
        {
            EventsService es = new EventsService();
            if (es.DeleteEventsService(eventId))
            {
                ViewBag.Message = "Trip deleted successfully";
                return RedirectToAction("Index");
            }
            return null;
        }
    }
}

Samuel_Yazie_SQL_Lab2/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Samuel_Yazie_SQL_Lab2.Models;

namespace Samuel_Yazie_SQL_Lab2.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return RedirectToAction("Index", "Events");
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Samuel_Yazie_SQL_Lab2/Controllers/RegistrationsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using IPBLL;
using IPENTITES;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace Samuel_Yazie_SQL_Lab2.Controllers
{
    public class RegistrationsController : Controller
    {
        // GET: /<controller>/
        public IActionResult Index(int eventId)
        {
            RegistrationService rs = new RegistrationService();
            var registrations = rs.GetRegistartions(eventId);

            return View(registrations);
        }

        public IActionResult CreateRegistrations()
        {
            return View();
        }

        [HttpPost]
        public IActionResult CreateRegistrations(Registartions registration)
        {
            if (ModelState.IsValid)
            {
                // Assuming you have a service to handle registration creation
                RegistrationService rs = new RegistrationService();
                if (rs.AddRegistrationsService(registration))
                {
                    ViewBag.Message = "Registration added successfully";
                    return RedirectToAction("Index", new { eventId = registration.EventId });
                }
            }
            return View();
        }


        /// <summary>
        /// EditRegistrationView is responsible for fetching the registration with the given registrationId and displaying it in the view
        /// </summary>
        /// <param name="registrationId"></param>
        /// <returns></returns>
        public IActionResult EditRegistrations(int eventId, int registrationId)
        {
            RegistrationService registrationService = new RegistrationService();
            // Fetch all the registrations and find the registration with the given registrationId
            var registration = registrationService.GetRegistration(eventId, registrationId);

            return View(registration);
        }

        /// <summary>
        /// EditRegistrationsView is responsible for updating the registration with the given registrationId and displaying it in the view
        /// and pass that to the service and repository to update the registration
        /// </summary>
        /// <param name="registration"></param>
        /// <returns></returns>
        [HttpPost]
        public IActionResult EditRegistrations(Registartions registration)
        {
            RegistrationService registrationService = new RegistrationService();
            if (registrationService.UpdateRegistrationsService(registration))
            {
                ViewBag.Message = "Registration updated successfully";
            }
            return RedirectToAction("Index", new { eventId = registration.EventId });
        }


        public IActionResult DeleteRegistration(int registrationId, int eventId)
        {
            RegistrationService rs = new RegistrationService();
            if (rs.DeleteRegistrationsService(registrationId))
            {
                ViewBag.Message = "Registration deleted successfully";
                return RedirectToAction("Index", new { eventId });
            }
            return View();
        }
    }
}

Samuel_Yazie_SQL_Lab2/Views/Events/CreateEventsView.cshtml
@model IPENTITES.Events

@{
    ViewBag.Title = "CreateEventView";
    ViewBag.Title = "Create Event";
}

<h2>CreateEventView</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Event</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.EventName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EventName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EventName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EventDescription, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EventDescription, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EventDescription, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EventDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EventDate, new { htmlAttributes = new { @class = "form-control", type = "date" } })
                @Html.ValidationMessageFor(model => model.EventDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EventLocation, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EventLocation, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EventLocation, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EventCapacity, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EventCapacity, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EventCapacity, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10" style="color:green">
            @ViewBag.Message
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Samuel_Yazie_SQL_Lab2/Views/Events/EditEventsView.cshtml
@model IPENTITES.Events

@{
    ViewBag.Title = "EditEventView";
}

<h2>EditEventView</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Event</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.EventId)

        <div class="form-group">
            @Html.LabelFor(model => model.EventName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EventName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EventName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EventDescription, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EventDescription, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EventDescription, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EventDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EventDate, new { htmlAttributes = new { @class = "form-control", type = "datetime" } })
                @Html.ValidationMessageFor(model => model.EventDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EventLocation, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EventLocation, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EventLocation, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EventCapacity, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EventCapacity, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EventCapacity, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10" style="color:green">
                @ViewBag.Message
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Samuel_Yazie_SQL_Lab2/Views/Events/Index.cshtml
@model IEnumerable<IPENTITES.Events>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>



<p>
    @Html.ActionLink("Create New", "CreateEventsView")
</p>
@* This table displays the trips on the database *@
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.EventName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EventDescription)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EventDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EventLocation)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EventCapacity)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.EventName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EventDescription)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EventDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EventLocation)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EventCapacity)
            </td>
            <td>
                @* Change eventId to match the EditEventView on the EventController *@
                @Html.ActionLink("Edit", "EditEventsView", new { eventId = item.EventId }) |
                @Html.ActionLink("Details", "Index", "Registrations", new { eventId = item.EventId }, null) |
                @Html.ActionLink("Delete", "DeleteEvent", new { eventId = item.EventId })
            </td>
        </tr>
    }
</table>

Samuel_Yazie_SQL_Lab2/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Samuel_Yazie_SQL_Lab2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Samuel_Yazie_SQL_Lab2</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Samuel_Yazie_SQL_Lab2.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Samuel_Yazie_SQL_Lab2</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Samuel_Yazie_SQL_Lab2 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>